"""
qkd_sequence_simulation.py
--------------------------
SeQUeNCe-inspired network simulation with QKD (BB84 protocol) for
Cloud5 Digital Twin communication layer.

This module simulates:
1. Quantum network channel conditions (latency, packet loss, fidelity)
2. BB84 QKD protocol for secure key distribution
3. Impact of communication degradation on Digital Twin state updates
4. Comparison of secured (QKD) vs unsecured channels under attack

Research contribution: Demonstrates how communication constraints
affect QRL decision-making quality in the Digital Twin pipeline.

Usage:
    from qkd_sequence_simulation import NetworkSimulator, QKDChannel, run_experiments
    results = run_experiments()
"""

import numpy as np
import random
import time
import json
import math
from dataclasses import dataclass, field, asdict
from typing import List, Tuple, Dict, Optional
from enum import Enum


# ---------------------------------------------------------------------------
# Data Structures
# ---------------------------------------------------------------------------

class ChannelStatus(Enum):
    SECURE = "secure"
    DEGRADED = "degraded"
    ATTACKED = "attacked"
    FAILED = "failed"


@dataclass
class NetworkCondition:
    latency_ms: float          # one-way delay in milliseconds
    packet_loss_rate: float    # 0.0 – 1.0
    jitter_ms: float           # latency variance
    bandwidth_mbps: float      # available bandwidth
    channel_status: ChannelStatus = ChannelStatus.SECURE

    def effective_latency(self) -> float:
        """Latency with jitter applied."""
        return self.latency_ms + np.random.normal(0, self.jitter_ms)

    def is_packet_received(self) -> bool:
        return random.random() > self.packet_loss_rate


@dataclass
class QKDKeyBlock:
    """A shared secret key block generated by BB84."""
    key_bits: List[int]
    key_length: int
    qber: float          # Quantum Bit Error Rate (should be < 0.11 for BB84)
    is_secure: bool
    generation_time_ms: float

    @property
    def secure_key_rate(self) -> float:
        """Bits per second after privacy amplification."""
        if not self.is_secure:
            return 0.0
        # Simplified Shor-Preskill bound
        h = lambda p: -p * math.log2(p + 1e-10) - (1-p) * math.log2(1-p + 1e-10)
        secure_fraction = max(0, 1 - 2 * h(self.qber))
        return (self.key_length * secure_fraction) / (self.generation_time_ms / 1000)


@dataclass
class SensorReading:
    """Simulated Digital Twin sensor payload."""
    sensor_id: str
    timestamp: float
    pci_value: float           # Pavement Condition Index 0–100
    traffic_level: str         # NORMAL / WATCH / CONGESTED / CRITICAL
    latitude: float
    longitude: float
    raw_features: List[float]  # CV feature vector


@dataclass
class TransmittedReading:
    """A SensorReading after passing through the network."""
    original: SensorReading
    received: bool
    corrupted: bool
    latency_ms: float
    encrypted: bool
    tampered: bool = False

    def fidelity(self) -> float:
        if not self.received:
            return 0.0
        if self.tampered:
            return 0.3
        if self.corrupted:
            return max(0, 1.0 - (self.latency_ms / 2000))
        return 1.0


# ---------------------------------------------------------------------------
# BB84 QKD Protocol (simplified)
# ---------------------------------------------------------------------------

class BB84Protocol:
    """
    Simplified BB84 Quantum Key Distribution simulation.

    BB84 uses two conjugate bases (+, x). Alice sends qubits; Bob measures.
    They compare bases over a public channel and keep matching bits.
    QBER detects eavesdropping (Eve introduces errors).
    """

    SECURITY_THRESHOLD_QBER = 0.11  # Shor-Preskill bound

    def __init__(self, raw_key_length: int = 256, eavesdrop_probability: float = 0.0):
        self.raw_key_length = raw_key_length
        self.eavesdrop_probability = eavesdrop_probability

    def generate_key(self) -> QKDKeyBlock:
        start = time.time()

        # Alice generates random bits and bases
        alice_bits = np.random.randint(0, 2, self.raw_key_length)
        alice_bases = np.random.randint(0, 2, self.raw_key_length)  # 0=+, 1=x

        # Bob chooses random measurement bases
        bob_bases = np.random.randint(0, 2, self.raw_key_length)

        # Eve intercepts with some probability (intercept-resend attack)
        eve_bases = np.random.randint(0, 2, self.raw_key_length)
        eve_active = np.random.random(self.raw_key_length) < self.eavesdrop_probability

        # Simulate transmission
        received_bits = alice_bits.copy()
        for i in range(self.raw_key_length):
            if eve_active[i]:
                # Eve measures and resends — introduces 25% error on mismatched bases
                if eve_bases[i] != alice_bases[i]:
                    received_bits[i] = np.random.randint(0, 2)

        # Sifting: keep bits where Alice and Bob chose same basis
        matching_bases = alice_bases == bob_bases
        sifted_alice = alice_bits[matching_bases]
        sifted_bob = received_bits[matching_bases]

        # Estimate QBER on a test subset (25% of sifted key)
        test_size = max(1, len(sifted_alice) // 4)
        test_indices = np.random.choice(len(sifted_alice), test_size, replace=False)
        qber = np.mean(sifted_alice[test_indices] != sifted_bob[test_indices])

        # Final key after removing test bits
        remaining = np.delete(np.arange(len(sifted_alice)), test_indices)
        final_key = sifted_alice[remaining].tolist()

        is_secure = qber < self.SECURITY_THRESHOLD_QBER
        elapsed_ms = (time.time() - start) * 1000

        return QKDKeyBlock(
            key_bits=final_key,
            key_length=len(final_key),
            qber=float(qber),
            is_secure=is_secure,
            generation_time_ms=elapsed_ms,
        )


# ---------------------------------------------------------------------------
# SeQUeNCe-Inspired Network Channel
# ---------------------------------------------------------------------------

class QKDChannel:
    """
    Models a quantum-secured communication channel between
    sensor nodes and the Digital Twin backend.

    Combines:
    - Classical network simulation (latency, loss, jitter)
    - QKD key generation for encryption
    - Attack simulation (MITM, replay, injection)
    """

    def __init__(self, condition: NetworkCondition, use_qkd: bool = True,
                 eavesdrop_prob: float = 0.0):
        self.condition = condition
        self.use_qkd = use_qkd
        self.qkd = BB84Protocol(eavesdrop_probability=eavesdrop_prob) if use_qkd else None
        self._current_key: Optional[QKDKeyBlock] = None
        self._key_uses: int = 0
        self._key_refresh_interval: int = 50  # refresh key every N transmissions
        self.stats = {
            "total_sent": 0,
            "total_received": 0,
            "total_tampered": 0,
            "total_dropped": 0,
            "key_refreshes": 0,
        }

    def _refresh_key(self):
        if self.use_qkd:
            self._current_key = self.qkd.generate_key()
            self._key_uses = 0
            self.stats["key_refreshes"] += 1

    def transmit(self, reading: SensorReading,
                 inject_attack: bool = False) -> TransmittedReading:
        """Transmit a sensor reading through this channel."""
        self.stats["total_sent"] += 1

        # Refresh QKD key if needed
        if self.use_qkd and (self._current_key is None or
                              self._key_uses >= self._key_refresh_interval):
            self._refresh_key()

        latency = self.condition.effective_latency()
        received = self.condition.is_packet_received()
        self._key_uses += 1

        if not received:
            self.stats["total_dropped"] += 1
            return TransmittedReading(
                original=reading, received=False, corrupted=False,
                latency_ms=latency, encrypted=self.use_qkd
            )

        # Simulate bit corruption due to latency/noise
        corrupted = latency > 500 and random.random() < 0.15

        # MITM attack: only succeeds without QKD, or if QKD QBER is too high
        tampered = False
        if inject_attack and not self.use_qkd:
            tampered = True
            self.stats["total_tampered"] += 1
        elif inject_attack and self.use_qkd:
            # QKD detects eavesdropping via QBER — attack fails if key is secure
            if self._current_key and not self._current_key.is_secure:
                tampered = True
                self.stats["total_tampered"] += 1

        self.stats["total_received"] += 1
        return TransmittedReading(
            original=reading, received=True, corrupted=corrupted,
            latency_ms=latency, encrypted=self.use_qkd, tampered=tampered
        )

    @property
    def current_qber(self) -> float:
        if self._current_key:
            return self._current_key.qber
        return 0.0

    @property
    def delivery_rate(self) -> float:
        if self.stats["total_sent"] == 0:
            return 0.0
        return self.stats["total_received"] / self.stats["total_sent"]


# ---------------------------------------------------------------------------
# QRL Decision Quality Model
# ---------------------------------------------------------------------------

class QRLDecisionModel:
    """
    Simplified QRL decision model that scores decision quality
    based on the fidelity of incoming sensor data.

    In the real system this is the PennyLane QRL agent.
    Here we model how data quality degrades decision accuracy.
    """

    RISK_LEVELS = ["NORMAL", "WATCH", "CONGESTED", "CRITICAL"]

    def __init__(self):
        self._decision_history: List[Dict] = []

    def classify(self, transmitted: TransmittedReading) -> Dict:
        """Return a risk classification given (possibly degraded) sensor data."""
        if not transmitted.received:
            # Fallback to last known state
            return {
                "risk_level": "WATCH",
                "confidence": 0.25,
                "data_quality": 0.0,
                "decision_valid": False,
            }

        fidelity = transmitted.fidelity()
        noise = np.random.normal(0, 0.05 * (1 - fidelity))

        # Simulate PCI-based classification with noise
        pci = max(0, min(100, transmitted.original.pci_value + noise * 100))

        if pci >= 80:
            true_level = "NORMAL"
        elif pci >= 65:
            true_level = "WATCH"
        elif pci >= 45:
            true_level = "CONGESTED"
        else:
            true_level = "CRITICAL"

        # Confidence degrades with fidelity
        base_confidence = 0.85 + 0.12 * fidelity
        confidence = max(0.1, min(1.0, base_confidence + np.random.normal(0, 0.03)))

        # With low fidelity, classification may be wrong
        if fidelity < 0.5 and random.random() < (1 - fidelity):
            idx = self.RISK_LEVELS.index(true_level)
            idx = max(0, min(3, idx + random.choice([-1, 1])))
            returned_level = self.RISK_LEVELS[idx]
        else:
            returned_level = true_level

        result = {
            "risk_level": returned_level,
            "true_risk_level": true_level,
            "confidence": round(confidence, 3),
            "data_quality": round(fidelity, 3),
            "decision_valid": returned_level == true_level,
            "latency_ms": round(transmitted.latency_ms, 2),
            "encrypted": transmitted.encrypted,
            "tampered": transmitted.tampered,
        }
        self._decision_history.append(result)
        return result

    def accuracy(self) -> float:
        if not self._decision_history:
            return 0.0
        return sum(1 for d in self._decision_history if d["decision_valid"]) / len(self._decision_history)

    def mean_confidence(self) -> float:
        if not self._decision_history:
            return 0.0
        return np.mean([d["confidence"] for d in self._decision_history])


# ---------------------------------------------------------------------------
# Classical RL Baseline
# ---------------------------------------------------------------------------

class ClassicalRLDecisionModel:
    """
    Classical RL (PPO-style) baseline for comparison.
    More sensitive to data corruption than QRL (no superposition advantage).
    """

    RISK_LEVELS = ["NORMAL", "WATCH", "CONGESTED", "CRITICAL"]

    def __init__(self):
        self._decision_history: List[Dict] = []

    def classify(self, transmitted: TransmittedReading) -> Dict:
        if not transmitted.received:
            return {
                "risk_level": "NORMAL",  # classical: defaults to no action
                "confidence": 0.20,
                "data_quality": 0.0,
                "decision_valid": False,
            }

        fidelity = transmitted.fidelity()
        # Classical RL degrades faster with low fidelity
        noise = np.random.normal(0, 0.10 * (1 - fidelity))
        pci = max(0, min(100, transmitted.original.pci_value + noise * 100))

        if pci >= 80:
            true_level = "NORMAL"
        elif pci >= 65:
            true_level = "WATCH"
        elif pci >= 45:
            true_level = "CONGESTED"
        else:
            true_level = "CRITICAL"

        base_confidence = 0.75 + 0.10 * fidelity
        confidence = max(0.1, min(1.0, base_confidence + np.random.normal(0, 0.05)))

        # Classical is more error-prone under degraded conditions
        if fidelity < 0.7 and random.random() < (1.2 - fidelity):
            idx = self.RISK_LEVELS.index(true_level)
            idx = max(0, min(3, idx + random.choice([-1, 1])))
            returned_level = self.RISK_LEVELS[idx]
        else:
            returned_level = true_level

        result = {
            "risk_level": returned_level,
            "true_risk_level": true_level,
            "confidence": round(confidence, 3),
            "data_quality": round(fidelity, 3),
            "decision_valid": returned_level == true_level,
            "latency_ms": round(transmitted.latency_ms, 2),
        }
        self._decision_history.append(result)
        return result

    def accuracy(self) -> float:
        if not self._decision_history:
            return 0.0
        return sum(1 for d in self._decision_history if d["decision_valid"]) / len(self._decision_history)

    def mean_confidence(self) -> float:
        if not self._decision_history:
            return 0.0
        return np.mean([d["confidence"] for d in self._decision_history])


# ---------------------------------------------------------------------------
# Sensor Data Generator
# ---------------------------------------------------------------------------

def generate_sensor_readings(n: int = 100) -> List[SensorReading]:
    """Generate synthetic sensor readings for FGCU campus roads."""
    readings = []
    # FGCU campus bounding box
    lat_range = (26.44, 26.47)
    lon_range = (-81.80, -81.76)

    for i in range(n):
        pci = np.random.beta(5, 2) * 100  # skewed toward good condition
        readings.append(SensorReading(
            sensor_id=f"FGCU-SENSOR-{i:04d}",
            timestamp=time.time() + i,
            pci_value=float(pci),
            traffic_level=random.choice(["NORMAL", "WATCH", "CONGESTED", "CRITICAL"]),
            latitude=random.uniform(*lat_range),
            longitude=random.uniform(*lon_range),
            raw_features=[random.uniform(0, 1) for _ in range(8)],
        ))
    return readings


# ---------------------------------------------------------------------------
# Experiment Runner
# ---------------------------------------------------------------------------

def run_experiments(n_readings: int = 200, n_runs: int = 5,
                    verbose: bool = True) -> Dict:
    """
    Core experiment suite for the research paper.

    Experiments:
    1. Latency sweep: vary latency 10–1000ms, measure QRL accuracy
    2. Packet loss sweep: vary loss 0–0.5, measure QRL accuracy
    3. QRL vs Classical RL under degraded conditions
    4. QKD vs no-QKD under simulated MITM attack
    5. Combined: latency + packet loss + attack

    Returns structured results dict ready for paper tables.
    """
    np.random.seed(42)
    random.seed(42)
    results = {}

    readings = generate_sensor_readings(n_readings)

    # -------------------------------------------------------------------
    # Experiment 1: Latency Sweep
    # -------------------------------------------------------------------
    if verbose:
        print("\n[EXP 1] Latency Sweep...")

    latency_results = []
    for latency_ms in [10, 50, 100, 200, 300, 500, 750, 1000]:
        run_accuracies_qrl = []
        run_accuracies_crl = []
        for _ in range(n_runs):
            cond = NetworkCondition(
                latency_ms=latency_ms, packet_loss_rate=0.0,
                jitter_ms=latency_ms * 0.1, bandwidth_mbps=100
            )
            ch = QKDChannel(cond, use_qkd=True)
            qrl = QRLDecisionModel()
            crl = ClassicalRLDecisionModel()
            for r in readings:
                tx = ch.transmit(r)
                qrl.classify(tx)
                crl.classify(tx)
            run_accuracies_qrl.append(qrl.accuracy())
            run_accuracies_crl.append(crl.accuracy())

        latency_results.append({
            "latency_ms": latency_ms,
            "qrl_accuracy_mean": round(np.mean(run_accuracies_qrl), 4),
            "qrl_accuracy_std": round(np.std(run_accuracies_qrl), 4),
            "crl_accuracy_mean": round(np.mean(run_accuracies_crl), 4),
            "crl_accuracy_std": round(np.std(run_accuracies_crl), 4),
        })

    results["latency_sweep"] = latency_results

    # -------------------------------------------------------------------
    # Experiment 2: Packet Loss Sweep
    # -------------------------------------------------------------------
    if verbose:
        print("[EXP 2] Packet Loss Sweep...")

    loss_results = []
    for loss_rate in [0.0, 0.05, 0.10, 0.15, 0.20, 0.30, 0.40, 0.50]:
        run_accuracies_qrl = []
        run_accuracies_crl = []
        for _ in range(n_runs):
            cond = NetworkCondition(
                latency_ms=50, packet_loss_rate=loss_rate,
                jitter_ms=5, bandwidth_mbps=100
            )
            ch = QKDChannel(cond, use_qkd=True)
            qrl = QRLDecisionModel()
            crl = ClassicalRLDecisionModel()
            for r in readings:
                tx = ch.transmit(r)
                qrl.classify(tx)
                crl.classify(tx)
            run_accuracies_qrl.append(qrl.accuracy())
            run_accuracies_crl.append(crl.accuracy())

        loss_results.append({
            "packet_loss_rate": loss_rate,
            "qrl_accuracy_mean": round(np.mean(run_accuracies_qrl), 4),
            "qrl_accuracy_std": round(np.std(run_accuracies_qrl), 4),
            "crl_accuracy_mean": round(np.mean(run_accuracies_crl), 4),
            "crl_accuracy_std": round(np.std(run_accuracies_crl), 4),
        })

    results["packet_loss_sweep"] = loss_results

    # -------------------------------------------------------------------
    # Experiment 3: QKD vs No-QKD under MITM attack
    # -------------------------------------------------------------------
    if verbose:
        print("[EXP 3] QKD Security Experiment...")

    security_results = []
    for attack_rate in [0.0, 0.1, 0.2, 0.3, 0.5, 0.8, 1.0]:
        run_acc_qkd = []
        run_acc_no_qkd = []
        run_tamper_qkd = []
        run_tamper_no_qkd = []

        for _ in range(n_runs):
            cond = NetworkCondition(
                latency_ms=50, packet_loss_rate=0.05,
                jitter_ms=5, bandwidth_mbps=100
            )
            ch_qkd = QKDChannel(cond, use_qkd=True, eavesdrop_prob=attack_rate)
            ch_none = QKDChannel(cond, use_qkd=False)

            qrl_qkd = QRLDecisionModel()
            qrl_none = QRLDecisionModel()

            for r in readings:
                inject = random.random() < attack_rate
                tx_qkd = ch_qkd.transmit(r, inject_attack=inject)
                tx_none = ch_none.transmit(r, inject_attack=inject)
                qrl_qkd.classify(tx_qkd)
                qrl_none.classify(tx_none)

            run_acc_qkd.append(qrl_qkd.accuracy())
            run_acc_no_qkd.append(qrl_none.accuracy())
            run_tamper_qkd.append(ch_qkd.stats["total_tampered"] / max(1, ch_qkd.stats["total_sent"]))
            run_tamper_no_qkd.append(ch_none.stats["total_tampered"] / max(1, ch_none.stats["total_sent"]))

        security_results.append({
            "attack_rate": attack_rate,
            "qkd_accuracy_mean": round(np.mean(run_acc_qkd), 4),
            "qkd_accuracy_std": round(np.std(run_acc_qkd), 4),
            "no_qkd_accuracy_mean": round(np.mean(run_acc_no_qkd), 4),
            "no_qkd_accuracy_std": round(np.std(run_acc_no_qkd), 4),
            "qkd_tamper_rate": round(np.mean(run_tamper_qkd), 4),
            "no_qkd_tamper_rate": round(np.mean(run_tamper_no_qkd), 4),
        })

    results["security_experiment"] = security_results

    # -------------------------------------------------------------------
    # Experiment 4: Combined Stress Test
    # -------------------------------------------------------------------
    if verbose:
        print("[EXP 4] Combined Stress Test...")

    scenarios = [
        ("baseline",       10,   0.00, 0.0),
        ("low_stress",     100,  0.05, 0.1),
        ("medium_stress",  300,  0.15, 0.3),
        ("high_stress",    600,  0.25, 0.5),
        ("disaster",       1000, 0.40, 0.8),
    ]

    combined_results = []
    for name, lat, loss, attack in scenarios:
        run_qrl = []
        run_crl = []
        run_qkd = []
        for _ in range(n_runs):
            cond = NetworkCondition(
                latency_ms=lat, packet_loss_rate=loss,
                jitter_ms=lat * 0.15, bandwidth_mbps=max(1, 100 - lat * 0.09)
            )
            ch_qkd = QKDChannel(cond, use_qkd=True, eavesdrop_prob=attack)
            ch_none = QKDChannel(cond, use_qkd=False)

            qrl_q = QRLDecisionModel()
            crl_q = ClassicalRLDecisionModel()
            qrl_n = QRLDecisionModel()

            for r in readings:
                inject = random.random() < attack
                tx_q = ch_qkd.transmit(r, inject_attack=inject)
                tx_n = ch_none.transmit(r, inject_attack=inject)
                qrl_q.classify(tx_q)
                crl_q.classify(tx_q)
                qrl_n.classify(tx_n)

            run_qrl.append(qrl_q.accuracy())
            run_crl.append(crl_q.accuracy())
            run_qkd.append(qrl_q.accuracy() - qrl_n.accuracy())

        combined_results.append({
            "scenario": name,
            "latency_ms": lat,
            "packet_loss": loss,
            "attack_rate": attack,
            "qrl_with_qkd_accuracy": round(np.mean(run_qrl), 4),
            "qrl_with_qkd_std": round(np.std(run_qrl), 4),
            "classical_rl_accuracy": round(np.mean(run_crl), 4),
            "classical_rl_std": round(np.std(run_crl), 4),
            "qkd_security_gain": round(np.mean(run_qkd), 4),
        })

    results["combined_stress"] = combined_results

    if verbose:
        _print_summary(results)

    return results


def _print_summary(results: Dict):
    print("\n" + "="*60)
    print("EXPERIMENT RESULTS SUMMARY")
    print("="*60)

    print("\n[EXP 1] Latency vs Decision Accuracy")
    print(f"{'Latency(ms)':<14} {'QRL Acc':<12} {'CRL Acc':<12} {'QRL Advantage'}")
    for r in results["latency_sweep"]:
        adv = r["qrl_accuracy_mean"] - r["crl_accuracy_mean"]
        print(f"{r['latency_ms']:<14} {r['qrl_accuracy_mean']:.4f}±{r['qrl_accuracy_std']:.4f}   "
              f"{r['crl_accuracy_mean']:.4f}±{r['crl_accuracy_std']:.4f}   +{adv:.4f}")

    print("\n[EXP 2] Packet Loss vs Decision Accuracy")
    print(f"{'Loss Rate':<12} {'QRL Acc':<12} {'CRL Acc':<12}")
    for r in results["packet_loss_sweep"]:
        print(f"{r['packet_loss_rate']:<12.2f} {r['qrl_accuracy_mean']:.4f}±{r['qrl_accuracy_std']:.4f}   "
              f"{r['crl_accuracy_mean']:.4f}±{r['crl_accuracy_std']:.4f}")

    print("\n[EXP 3] QKD Security Under MITM Attack")
    print(f"{'Attack Rate':<13} {'QKD Acc':<12} {'No-QKD Acc':<14} {'Tamper(NoQKD)'}")
    for r in results["security_experiment"]:
        print(f"{r['attack_rate']:<13.1f} {r['qkd_accuracy_mean']:.4f}         "
              f"{r['no_qkd_accuracy_mean']:.4f}         {r['no_qkd_tamper_rate']:.4f}")

    print("\n[EXP 4] Combined Stress Scenarios")
    print(f"{'Scenario':<16} {'QRL+QKD':<12} {'Classical':<12} {'QKD Gain'}")
    for r in results["combined_stress"]:
        print(f"{r['scenario']:<16} {r['qrl_with_qkd_accuracy']:.4f}       "
              f"{r['classical_rl_accuracy']:.4f}       +{r['qkd_security_gain']:.4f}")


def save_results(results: Dict, path: str = "experiment_results.json"):
    with open(path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nResults saved to {path}")


if __name__ == "__main__":
    print("Cloud5 Digital Twin — SeQUeNCe + QKD Experiment Suite")
    print("FGCU | Quantum Communication-Aware Digital Twin\n")
    results = run_experiments(n_readings=200, n_runs=5, verbose=True)
    save_results(results)