"""
qkd_sequence_simulation.py
--------------------------
SeQUeNCe-inspired network simulation with QKD (BB84 protocol) for
Cloud5 Digital Twin communication layer.

This module simulates:
1. Quantum network channel conditions (latency, packet loss, fidelity)
2. BB84 QKD protocol for secure key distribution
3. Impact of communication degradation on Digital Twin state updates
4. Comparison of secured (QKD) vs unsecured channels under attack

Research contribution: Demonstrates how communication constraints
affect QRL decision-making quality in the Digital Twin pipeline.

Usage:
    from qkd_sequence_simulation import NetworkSimulator, QKDChannel, run_experiments
    results = run_experiments()
"""

import numpy as np
import random
import time
import json
import math
from dataclasses import dataclass, field, asdict
from typing import List, Tuple, Dict, Optional
from enum import Enum


# ---------------------------------------------------------------------------
# Data Structures
# ---------------------------------------------------------------------------

class ChannelStatus(Enum):
    SECURE = "secure"
    DEGRADED = "degraded"
    ATTACKED = "attacked"
    FAILED = "failed"


@dataclass
class NetworkCondition:
    latency_ms: float          # one-way delay in milliseconds
    packet_loss_rate: float    # 0.0 – 1.0
    jitter_ms: float           # latency variance
    bandwidth_mbps: float      # available bandwidth
    channel_status: ChannelStatus = ChannelStatus.SECURE

    def effective_latency(self) -> float:
        """Latency with jitter applied."""
        return self.latency_ms + np.random.normal(0, self.jitter_ms)

    def is_packet_received(self) -> bool:
        return random.random() > self.packet_loss_rate


@dataclass
class QKDKeyBlock:
    """A shared secret key block generated by BB84."""
    key_bits: List[int]
    key_length: int
    qber: float          # Quantum Bit Error Rate (should be < 0.11 for BB84)
    is_secure: bool
    generation_time_ms: float

    @property
    def secure_key_rate(self) -> float:
        """Bits per second after privacy amplification."""
        if not self.is_secure:
            return 0.0
        # Simplified Shor-Preskill bound
        h = lambda p: -p * math.log2(p + 1e-10) - (1-p) * math.log2(1-p + 1e-10)
        secure_fraction = max(0, 1 - 2 * h(self.qber))
        return (self.key_length * secure_fraction) / (self.generation_time_ms / 1000)


@dataclass
class SensorReading:
    """Simulated Digital Twin sensor payload."""
    sensor_id: str
    timestamp: float
    pci_value: float           # Pavement Condition Index 0–100
    traffic_level: str         # NORMAL / WATCH / CONGESTED / CRITICAL
    latitude: float
    longitude: float
    raw_features: List[float]  # CV feature vector


@dataclass
class TransmittedReading:
    """A SensorReading after passing through the network."""
    original: SensorReading
    received: bool
    corrupted: bool
    latency_ms: float
    encrypted: bool
    tampered: bool = False

    def fidelity(self) -> float:
        if not self.received:
            return 0.0
        if self.tampered:
            return 0.3
        if self.corrupted:
            return max(0, 1.0 - (self.latency_ms / 2000))
        return 1.0


# ---------------------------------------------------------------------------
# Statistics Helpers
# ---------------------------------------------------------------------------

# t-distribution critical values for 95% CI (two-tailed), indexed by df (1..30+)
_T_CRIT_95 = {
    1: 12.706, 2: 4.303, 3: 3.182, 4: 2.776, 5: 2.571,
    6: 2.447,  7: 2.365, 8: 2.306, 9: 2.262, 10: 2.228,
    11: 2.201, 12: 2.179, 13: 2.160, 14: 2.145, 15: 2.131,
    16: 2.120, 17: 2.110, 18: 2.101, 19: 2.093, 20: 2.086,
    25: 2.060, 30: 2.042,
}


def _t_crit(n: int) -> float:
    """95% CI t critical value for n observations."""
    df = n - 1
    if df <= 0:
        return 1.96
    if df in _T_CRIT_95:
        return _T_CRIT_95[df]
    if df > 30:
        return 1.96
    # Linear interpolation between nearest tabulated values
    keys = sorted(_T_CRIT_95.keys())
    for i in range(len(keys) - 1):
        if keys[i] <= df < keys[i+1]:
            lo, hi = keys[i], keys[i+1]
            t = (df - lo) / (hi - lo)
            return _T_CRIT_95[lo] + t * (_T_CRIT_95[hi] - _T_CRIT_95[lo])
    return 1.96


def confidence_interval_95(values: List[float]) -> Tuple[float, float]:
    """Return (lower, upper) 95% confidence interval using t-distribution."""
    n = len(values)
    if n < 2:
        m = float(np.mean(values)) if values else 0.0
        return (m, m)
    mean = float(np.mean(values))
    se = float(np.std(values, ddof=1)) / math.sqrt(n)
    margin = _t_crit(n) * se
    return (round(mean - margin, 4), round(mean + margin, 4))


def _ci_dict(values: List[float], prefix: str) -> Dict:
    """Return mean, std, and 95% CI fields for a metric."""
    lo, hi = confidence_interval_95(values)
    return {
        f"{prefix}_mean": round(float(np.mean(values)), 4),
        f"{prefix}_std":  round(float(np.std(values)), 4),
        f"{prefix}_ci95_lower": lo,
        f"{prefix}_ci95_upper": hi,
    }


# ---------------------------------------------------------------------------
# BB84 QKD Protocol (simplified)
# ---------------------------------------------------------------------------

class BB84Protocol:
    """
    Simplified BB84 Quantum Key Distribution simulation.

    BB84 uses two conjugate bases (+, x). Alice sends qubits; Bob measures.
    They compare bases over a public channel and keep matching bits.
    QBER detects eavesdropping (Eve introduces errors).
    """

    SECURITY_THRESHOLD_QBER = 0.11  # Shor-Preskill bound

    def __init__(self, raw_key_length: int = 256, eavesdrop_probability: float = 0.0):
        self.raw_key_length = raw_key_length
        self.eavesdrop_probability = eavesdrop_probability

    def generate_key(self) -> QKDKeyBlock:
        start = time.time()

        # Alice generates random bits and bases
        alice_bits = np.random.randint(0, 2, self.raw_key_length)
        alice_bases = np.random.randint(0, 2, self.raw_key_length)  # 0=+, 1=x

        # Bob chooses random measurement bases
        bob_bases = np.random.randint(0, 2, self.raw_key_length)

        # Eve intercepts with some probability (intercept-resend attack)
        eve_bases = np.random.randint(0, 2, self.raw_key_length)
        eve_active = np.random.random(self.raw_key_length) < self.eavesdrop_probability

        # Simulate transmission
        received_bits = alice_bits.copy()
        for i in range(self.raw_key_length):
            if eve_active[i]:
                # Eve measures and resends — introduces 25% error on mismatched bases
                if eve_bases[i] != alice_bases[i]:
                    received_bits[i] = np.random.randint(0, 2)

        # Sifting: keep bits where Alice and Bob chose same basis
        matching_bases = alice_bases == bob_bases
        sifted_alice = alice_bits[matching_bases]
        sifted_bob = received_bits[matching_bases]

        # Estimate QBER on a test subset (25% of sifted key)
        test_size = max(1, len(sifted_alice) // 4)
        test_indices = np.random.choice(len(sifted_alice), test_size, replace=False)
        qber = np.mean(sifted_alice[test_indices] != sifted_bob[test_indices])

        # Final key after removing test bits
        remaining = np.delete(np.arange(len(sifted_alice)), test_indices)
        final_key = sifted_alice[remaining].tolist()

        is_secure = qber < self.SECURITY_THRESHOLD_QBER
        elapsed_ms = (time.time() - start) * 1000

        return QKDKeyBlock(
            key_bits=final_key,
            key_length=len(final_key),
            qber=float(qber),
            is_secure=is_secure,
            generation_time_ms=elapsed_ms,
        )


# ---------------------------------------------------------------------------
# SeQUeNCe-Inspired Network Channel
# ---------------------------------------------------------------------------

class QKDChannel:
    """
    Models a quantum-secured communication channel between
    sensor nodes and the Digital Twin backend.

    Combines:
    - Classical network simulation (latency, loss, jitter)
    - QKD key generation for encryption
    - Attack simulation (MITM, replay, injection)
    """

    def __init__(self, condition: NetworkCondition, use_qkd: bool = True,
                 eavesdrop_prob: float = 0.0):
        self.condition = condition
        self.use_qkd = use_qkd
        self.qkd = BB84Protocol(eavesdrop_probability=eavesdrop_prob) if use_qkd else None
        self._current_key: Optional[QKDKeyBlock] = None
        self._key_uses: int = 0
        self._key_refresh_interval: int = 50  # refresh key every N transmissions
        self.stats = {
            "total_sent": 0,
            "total_received": 0,
            "total_tampered": 0,
            "total_dropped": 0,
            "key_refreshes": 0,
        }

    def _refresh_key(self):
        if self.use_qkd:
            self._current_key = self.qkd.generate_key()
            self._key_uses = 0
            self.stats["key_refreshes"] += 1

    def transmit(self, reading: SensorReading,
                 inject_attack: bool = False) -> TransmittedReading:
        """Transmit a sensor reading through this channel."""
        self.stats["total_sent"] += 1

        # Refresh QKD key if needed
        if self.use_qkd and (self._current_key is None or
                              self._key_uses >= self._key_refresh_interval):
            self._refresh_key()

        latency = self.condition.effective_latency()
        received = self.condition.is_packet_received()
        self._key_uses += 1

        if not received:
            self.stats["total_dropped"] += 1
            return TransmittedReading(
                original=reading, received=False, corrupted=False,
                latency_ms=latency, encrypted=self.use_qkd
            )

        # Simulate bit corruption due to latency/noise
        corrupted = latency > 500 and random.random() < 0.15

        # MITM attack: only succeeds without QKD, or if QKD QBER is too high
        tampered = False
        if inject_attack and not self.use_qkd:
            tampered = True
            self.stats["total_tampered"] += 1
        elif inject_attack and self.use_qkd:
            # QKD detects eavesdropping via QBER — attack fails if key is secure
            if self._current_key and not self._current_key.is_secure:
                tampered = True
                self.stats["total_tampered"] += 1

        self.stats["total_received"] += 1
        return TransmittedReading(
            original=reading, received=True, corrupted=corrupted,
            latency_ms=latency, encrypted=self.use_qkd, tampered=tampered
        )

    @property
    def current_qber(self) -> float:
        if self._current_key:
            return self._current_key.qber
        return 0.0

    @property
    def delivery_rate(self) -> float:
        if self.stats["total_sent"] == 0:
            return 0.0
        return self.stats["total_received"] / self.stats["total_sent"]


# ---------------------------------------------------------------------------
# QRL Decision Quality Model
# ---------------------------------------------------------------------------

class QRLDecisionModel:
    """
    Simplified QRL decision model that scores decision quality
    based on the fidelity of incoming sensor data.

    In the real system this is the PennyLane QRL agent.
    Here we model how data quality degrades decision accuracy.
    """

    RISK_LEVELS = ["NORMAL", "WATCH", "CONGESTED", "CRITICAL"]

    def __init__(self):
        self._decision_history: List[Dict] = []

    def classify(self, transmitted: TransmittedReading) -> Dict:
        """Return a risk classification given (possibly degraded) sensor data."""
        if not transmitted.received:
            # Fallback to last known state
            return {
                "risk_level": "WATCH",
                "confidence": 0.25,
                "data_quality": 0.0,
                "decision_valid": False,
            }

        fidelity = transmitted.fidelity()
        noise = np.random.normal(0, 0.05 * (1 - fidelity))

        # Simulate PCI-based classification with noise
        pci = max(0, min(100, transmitted.original.pci_value + noise * 100))

        if pci >= 80:
            true_level = "NORMAL"
        elif pci >= 65:
            true_level = "WATCH"
        elif pci >= 45:
            true_level = "CONGESTED"
        else:
            true_level = "CRITICAL"

        # Confidence degrades with fidelity
        base_confidence = 0.85 + 0.12 * fidelity
        confidence = max(0.1, min(1.0, base_confidence + np.random.normal(0, 0.03)))

        # With low fidelity, classification may be wrong
        if fidelity < 0.5 and random.random() < (1 - fidelity):
            idx = self.RISK_LEVELS.index(true_level)
            idx = max(0, min(3, idx + random.choice([-1, 1])))
            returned_level = self.RISK_LEVELS[idx]
        else:
            returned_level = true_level

        result = {
            "risk_level": returned_level,
            "true_risk_level": true_level,
            "confidence": round(confidence, 3),
            "data_quality": round(fidelity, 3),
            "decision_valid": returned_level == true_level,
            "latency_ms": round(transmitted.latency_ms, 2),
            "encrypted": transmitted.encrypted,
            "tampered": transmitted.tampered,
        }
        self._decision_history.append(result)
        return result

    def accuracy(self) -> float:
        if not self._decision_history:
            return 0.0
        return sum(1 for d in self._decision_history if d["decision_valid"]) / len(self._decision_history)

    def mean_confidence(self) -> float:
        if not self._decision_history:
            return 0.0
        return np.mean([d["confidence"] for d in self._decision_history])

    def global_efficiency(self) -> float:
        """Accuracy on NORMAL/WATCH (routine) conditions — global optimality proxy."""
        routine = [d for d in self._decision_history
                   if d.get("true_risk_level") in ("NORMAL", "WATCH")]
        if not routine:
            return 0.0
        return sum(1 for d in routine if d["decision_valid"]) / len(routine)

    def local_safety(self) -> float:
        """Accuracy on CONGESTED/CRITICAL conditions — safety-critical proxy."""
        critical = [d for d in self._decision_history
                    if d.get("true_risk_level") in ("CONGESTED", "CRITICAL")]
        if not critical:
            return 0.0
        return sum(1 for d in critical if d["decision_valid"]) / len(critical)


# ---------------------------------------------------------------------------
# PPO Classical Baseline (with GAE lambda)
# ---------------------------------------------------------------------------

class PPODecisionModel:
    """
    PPO (Proximal Policy Optimization) classical RL baseline for comparison.

    lambda_param mirrors the GAE lambda hyperparameter (λ ∈ [0, ∞)):
      - λ → 0  : TD(0)-like; low variance, higher bias; stable under noise
      - λ = 0.5: moderate bias-variance tradeoff
      - λ = 1.0: MC-like; unbiased but sensitive to noisy observations
      - λ > 1  : over-weighted future returns; highly noise-sensitive

    Compared to QRL, PPO lacks the superposition advantage and degrades
    faster under degraded communication conditions.
    """

    RISK_LEVELS = ["NORMAL", "WATCH", "CONGESTED", "CRITICAL"]

    def __init__(self, lambda_param: float = 1.0):
        self.lambda_param = lambda_param
        self._decision_history: List[Dict] = []

    def classify(self, transmitted: TransmittedReading) -> Dict:
        if not transmitted.received:
            return {
                "risk_level": "NORMAL",   # classical: defaults to no action
                "confidence": 0.20,
                "data_quality": 0.0,
                "decision_valid": False,
                "lambda_param": self.lambda_param,
            }

        fidelity = transmitted.fidelity()

        # Higher lambda → more sensitive to noise (less regularized)
        noise_scale = 0.08 * self.lambda_param * (1 - fidelity)
        noise = np.random.normal(0, noise_scale)
        pci = max(0, min(100, transmitted.original.pci_value + noise * 100))

        if pci >= 80:
            true_level = "NORMAL"
        elif pci >= 65:
            true_level = "WATCH"
        elif pci >= 45:
            true_level = "CONGESTED"
        else:
            true_level = "CRITICAL"

        # Confidence: higher lambda → more variance → wider spread
        base_conf = 0.75 + 0.10 * fidelity - 0.01 * self.lambda_param
        conf_noise = np.random.normal(0, 0.03 * min(self.lambda_param, 2.0))
        confidence = max(0.1, min(1.0, base_conf + conf_noise))

        # Misclassification probability: lambda scales how badly noise hurts
        mis_prob = (1.2 - fidelity) * min(1.0, self.lambda_param * 0.45)
        if fidelity < 0.7 and random.random() < mis_prob:
            idx = self.RISK_LEVELS.index(true_level)
            idx = max(0, min(3, idx + random.choice([-1, 1])))
            returned_level = self.RISK_LEVELS[idx]
        else:
            returned_level = true_level

        result = {
            "risk_level": returned_level,
            "true_risk_level": true_level,
            "confidence": round(confidence, 3),
            "data_quality": round(fidelity, 3),
            "decision_valid": returned_level == true_level,
            "latency_ms": round(transmitted.latency_ms, 2),
            "lambda_param": self.lambda_param,
        }
        self._decision_history.append(result)
        return result

    def accuracy(self) -> float:
        if not self._decision_history:
            return 0.0
        return sum(1 for d in self._decision_history if d["decision_valid"]) / len(self._decision_history)

    def mean_confidence(self) -> float:
        if not self._decision_history:
            return 0.0
        return float(np.mean([d["confidence"] for d in self._decision_history]))

    def global_efficiency(self) -> float:
        """Accuracy on NORMAL/WATCH (routine) conditions — global optimality proxy."""
        routine = [d for d in self._decision_history
                   if d.get("true_risk_level") in ("NORMAL", "WATCH")]
        if not routine:
            return 0.0
        return sum(1 for d in routine if d["decision_valid"]) / len(routine)

    def local_safety(self) -> float:
        """Accuracy on CONGESTED/CRITICAL conditions — safety-critical proxy."""
        critical = [d for d in self._decision_history
                    if d.get("true_risk_level") in ("CONGESTED", "CRITICAL")]
        if not critical:
            return 0.0
        return sum(1 for d in critical if d["decision_valid"]) / len(critical)


# Keep alias for backward compatibility
ClassicalRLDecisionModel = PPODecisionModel


# ---------------------------------------------------------------------------
# Sensor Data Generator
# ---------------------------------------------------------------------------

def generate_sensor_readings(n: int = 100) -> List[SensorReading]:
    """Generate synthetic sensor readings for FGCU campus roads."""
    readings = []
    # FGCU campus bounding box
    lat_range = (26.44, 26.47)
    lon_range = (-81.80, -81.76)

    for i in range(n):
        pci = np.random.beta(5, 2) * 100  # skewed toward good condition
        readings.append(SensorReading(
            sensor_id=f"FGCU-SENSOR-{i:04d}",
            timestamp=time.time() + i,
            pci_value=float(pci),
            traffic_level=random.choice(["NORMAL", "WATCH", "CONGESTED", "CRITICAL"]),
            latitude=random.uniform(*lat_range),
            longitude=random.uniform(*lon_range),
            raw_features=[random.uniform(0, 1) for _ in range(8)],
        ))
    return readings


# ---------------------------------------------------------------------------
# Experiment Runner
# ---------------------------------------------------------------------------

def run_experiments(n_readings: int = 200, n_runs: int = 10,
                    verbose: bool = True) -> Dict:
    """
    Core experiment suite for the research paper.

    Experiments:
    1. Latency sweep: vary latency 10–1000ms, measure QRL accuracy
    2. Packet loss sweep: vary loss 0–0.5, measure QRL vs PPO accuracy
    3. QKD vs no-QKD under simulated MITM attack
    4. Combined: latency + packet loss + attack
    5. PPO lambda sweep: vary GAE lambda {0.1, 0.5, 1.0, 2.0} vs QRL

    All results include 95% confidence intervals (t-distribution).
    Returns structured results dict ready for paper tables.
    """
    np.random.seed(42)
    random.seed(42)
    results = {
        "metadata": {
            "n_readings": n_readings,
            "n_runs": n_runs,
            "ci_level": "95%",
            "ci_method": "t-distribution",
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        }
    }

    readings = generate_sensor_readings(n_readings)

    # -------------------------------------------------------------------
    # Experiment 1: Latency Sweep
    # -------------------------------------------------------------------
    if verbose:
        print("\n[EXP 1] Latency Sweep...")

    latency_results = []
    for latency_ms in [10, 50, 100, 200, 300, 500, 750, 1000]:
        run_accuracies_qrl = []
        run_accuracies_ppo = []
        for _ in range(n_runs):
            cond = NetworkCondition(
                latency_ms=latency_ms, packet_loss_rate=0.0,
                jitter_ms=latency_ms * 0.1, bandwidth_mbps=100
            )
            ch = QKDChannel(cond, use_qkd=True)
            qrl = QRLDecisionModel()
            ppo = PPODecisionModel(lambda_param=1.0)
            for r in readings:
                tx = ch.transmit(r)
                qrl.classify(tx)
                ppo.classify(tx)
            run_accuracies_qrl.append(qrl.accuracy())
            run_accuracies_ppo.append(ppo.accuracy())

        row = {"latency_ms": latency_ms}
        row.update(_ci_dict(run_accuracies_qrl, "qrl_accuracy"))
        row.update(_ci_dict(run_accuracies_ppo, "ppo_accuracy"))
        # Backward-compat aliases
        row["crl_accuracy_mean"] = row["ppo_accuracy_mean"]
        row["crl_accuracy_std"]  = row["ppo_accuracy_std"]
        latency_results.append(row)

    results["latency_sweep"] = latency_results

    # -------------------------------------------------------------------
    # Experiment 2: Packet Loss Sweep
    # -------------------------------------------------------------------
    if verbose:
        print("[EXP 2] Packet Loss Sweep...")

    loss_results = []
    for loss_rate in [0.0, 0.05, 0.10, 0.15, 0.20, 0.30, 0.40, 0.50]:
        run_accuracies_qrl = []
        run_accuracies_ppo = []
        for _ in range(n_runs):
            cond = NetworkCondition(
                latency_ms=50, packet_loss_rate=loss_rate,
                jitter_ms=5, bandwidth_mbps=100
            )
            ch = QKDChannel(cond, use_qkd=True)
            qrl = QRLDecisionModel()
            ppo = PPODecisionModel(lambda_param=1.0)
            for r in readings:
                tx = ch.transmit(r)
                qrl.classify(tx)
                ppo.classify(tx)
            run_accuracies_qrl.append(qrl.accuracy())
            run_accuracies_ppo.append(ppo.accuracy())

        row = {"packet_loss_rate": loss_rate}
        row.update(_ci_dict(run_accuracies_qrl, "qrl_accuracy"))
        row.update(_ci_dict(run_accuracies_ppo, "ppo_accuracy"))
        row["crl_accuracy_mean"] = row["ppo_accuracy_mean"]
        row["crl_accuracy_std"]  = row["ppo_accuracy_std"]
        loss_results.append(row)

    results["packet_loss_sweep"] = loss_results

    # -------------------------------------------------------------------
    # Experiment 3: QKD vs No-QKD under MITM attack
    # -------------------------------------------------------------------
    if verbose:
        print("[EXP 3] QKD Security Experiment...")

    security_results = []
    for attack_rate in [0.0, 0.1, 0.2, 0.3, 0.5, 0.8, 1.0]:
        run_acc_qkd    = []
        run_acc_no_qkd = []
        run_tamper_qkd     = []
        run_tamper_no_qkd  = []

        for _ in range(n_runs):
            cond = NetworkCondition(
                latency_ms=50, packet_loss_rate=0.05,
                jitter_ms=5, bandwidth_mbps=100
            )
            ch_qkd  = QKDChannel(cond, use_qkd=True,  eavesdrop_prob=attack_rate)
            ch_none = QKDChannel(cond, use_qkd=False)

            qrl_qkd  = QRLDecisionModel()
            qrl_none = QRLDecisionModel()

            for r in readings:
                inject = random.random() < attack_rate
                tx_qkd  = ch_qkd.transmit(r,  inject_attack=inject)
                tx_none = ch_none.transmit(r, inject_attack=inject)
                qrl_qkd.classify(tx_qkd)
                qrl_none.classify(tx_none)

            run_acc_qkd.append(qrl_qkd.accuracy())
            run_acc_no_qkd.append(qrl_none.accuracy())
            run_tamper_qkd.append(
                ch_qkd.stats["total_tampered"] / max(1, ch_qkd.stats["total_sent"]))
            run_tamper_no_qkd.append(
                ch_none.stats["total_tampered"] / max(1, ch_none.stats["total_sent"]))

        row = {"attack_rate": attack_rate}
        row.update(_ci_dict(run_acc_qkd,    "qkd_accuracy"))
        row.update(_ci_dict(run_acc_no_qkd, "no_qkd_accuracy"))
        row["qkd_tamper_rate"]    = round(float(np.mean(run_tamper_qkd)), 4)
        row["no_qkd_tamper_rate"] = round(float(np.mean(run_tamper_no_qkd)), 4)
        security_results.append(row)

    results["security_experiment"] = security_results

    # -------------------------------------------------------------------
    # Experiment 4: Combined Stress Test
    # -------------------------------------------------------------------
    if verbose:
        print("[EXP 4] Combined Stress Test...")

    scenarios = [
        ("baseline",       10,   0.00, 0.0),
        ("low_stress",     100,  0.05, 0.1),
        ("medium_stress",  300,  0.15, 0.3),
        ("high_stress",    600,  0.25, 0.5),
        ("disaster",       1000, 0.40, 0.8),
    ]

    combined_results = []
    for name, lat, loss, attack in scenarios:
        run_qrl = []
        run_ppo = []
        run_qkd_gain = []
        for _ in range(n_runs):
            cond = NetworkCondition(
                latency_ms=lat, packet_loss_rate=loss,
                jitter_ms=lat * 0.15, bandwidth_mbps=max(1, 100 - lat * 0.09)
            )
            ch_qkd  = QKDChannel(cond, use_qkd=True,  eavesdrop_prob=attack)
            ch_none = QKDChannel(cond, use_qkd=False)

            qrl_q = QRLDecisionModel()
            ppo_q = PPODecisionModel(lambda_param=1.0)
            qrl_n = QRLDecisionModel()

            for r in readings:
                inject = random.random() < attack
                tx_q = ch_qkd.transmit(r, inject_attack=inject)
                tx_n = ch_none.transmit(r, inject_attack=inject)
                qrl_q.classify(tx_q)
                ppo_q.classify(tx_q)
                qrl_n.classify(tx_n)

            run_qrl.append(qrl_q.accuracy())
            run_ppo.append(ppo_q.accuracy())
            run_qkd_gain.append(qrl_q.accuracy() - qrl_n.accuracy())

        row = {
            "scenario": name,
            "latency_ms": lat,
            "packet_loss": loss,
            "attack_rate": attack,
        }
        row.update(_ci_dict(run_qrl,      "qrl_with_qkd_accuracy"))
        row.update(_ci_dict(run_ppo,      "ppo_accuracy"))
        row.update(_ci_dict(run_qkd_gain, "qkd_security_gain"))
        # Backward-compat aliases
        row["classical_rl_accuracy"] = row["ppo_accuracy_mean"]
        row["classical_rl_std"]      = row["ppo_accuracy_std"]
        combined_results.append(row)

    results["combined_stress"] = combined_results

    # -------------------------------------------------------------------
    # Experiment 5: PPO Lambda Sweep vs QRL
    # -------------------------------------------------------------------
    if verbose:
        print("[EXP 5] PPO Lambda Sweep (λ ∈ {0.1, 0.5, 1.0, 2.0})...")

    lambda_values = [0.1, 0.5, 1.0, 2.0]

    # Run across three representative network conditions
    lambda_scenarios = [
        ("clean",    50,  0.00, 0.0),
        ("degraded", 300, 0.15, 0.3),
        ("attacked", 100, 0.05, 0.8),
    ]

    lambda_results = []
    for lam in lambda_values:
        for sc_name, lat, loss, attack in lambda_scenarios:
            run_ppo_acc = []
            run_qrl_acc = []
            run_ppo_conf = []
            run_qrl_conf = []
            run_ppo_glob = []
            run_ppo_safe = []
            run_qrl_glob = []
            run_qrl_safe = []

            for _ in range(n_runs):
                cond = NetworkCondition(
                    latency_ms=lat, packet_loss_rate=loss,
                    jitter_ms=lat * 0.1, bandwidth_mbps=max(1, 100 - lat * 0.09)
                )
                ch = QKDChannel(cond, use_qkd=True, eavesdrop_prob=attack)
                ppo = PPODecisionModel(lambda_param=lam)
                qrl = QRLDecisionModel()

                for r in readings:
                    inject = random.random() < attack
                    tx = ch.transmit(r, inject_attack=inject)
                    ppo.classify(tx)
                    qrl.classify(tx)

                run_ppo_acc.append(ppo.accuracy())
                run_qrl_acc.append(qrl.accuracy())
                run_ppo_conf.append(ppo.mean_confidence())
                run_qrl_conf.append(qrl.mean_confidence())
                run_ppo_glob.append(ppo.global_efficiency())
                run_ppo_safe.append(ppo.local_safety())
                run_qrl_glob.append(qrl.global_efficiency())
                run_qrl_safe.append(qrl.local_safety())

            row = {
                "lambda_param": lam,
                "scenario": sc_name,
                "latency_ms": lat,
                "packet_loss": loss,
                "attack_rate": attack,
            }
            row.update(_ci_dict(run_ppo_acc,  "ppo_accuracy"))
            row.update(_ci_dict(run_qrl_acc,  "qrl_accuracy"))
            row.update(_ci_dict(run_ppo_conf, "ppo_confidence"))
            row.update(_ci_dict(run_qrl_conf, "qrl_confidence"))
            row.update(_ci_dict(run_ppo_glob, "ppo_global_efficiency"))
            row.update(_ci_dict(run_ppo_safe, "ppo_local_safety"))
            row.update(_ci_dict(run_qrl_glob, "qrl_global_efficiency"))
            row.update(_ci_dict(run_qrl_safe, "qrl_local_safety"))
            row["qrl_advantage_mean"] = round(
                row["qrl_accuracy_mean"] - row["ppo_accuracy_mean"], 4)
            # Policy shift: how lambda pulls PPO toward local safety vs global efficiency
            row["ppo_safety_efficiency_ratio"] = round(
                row["ppo_local_safety_mean"] / max(1e-6, row["ppo_global_efficiency_mean"]), 4)
            lambda_results.append(row)

    results["ppo_lambda_sweep"] = lambda_results

    # -------------------------------------------------------------------
    # Experiment 6: SeQUeNCe Sensitivity — Packet Loss vs QRL/PPO Gap
    # -------------------------------------------------------------------
    if verbose:
        print("[EXP 6] SeQUeNCe Sensitivity (packet loss sweep, QRL vs PPO gap)...")

    seq_loss_results = []
    for loss_rate in [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]:
        run_qrl_acc = []
        run_ppo_acc = []
        run_qrl_safe = []
        run_ppo_safe = []
        run_qrl_glob = []
        run_ppo_glob = []

        for _ in range(n_runs):
            cond = NetworkCondition(
                latency_ms=50, packet_loss_rate=loss_rate,
                jitter_ms=5, bandwidth_mbps=100
            )
            ch = QKDChannel(cond, use_qkd=True)
            qrl = QRLDecisionModel()
            ppo = PPODecisionModel(lambda_param=1.0)

            for r in readings:
                tx = ch.transmit(r)
                qrl.classify(tx)
                ppo.classify(tx)

            run_qrl_acc.append(qrl.accuracy())
            run_ppo_acc.append(ppo.accuracy())
            run_qrl_safe.append(qrl.local_safety())
            run_ppo_safe.append(ppo.local_safety())
            run_qrl_glob.append(qrl.global_efficiency())
            run_ppo_glob.append(ppo.global_efficiency())

        row = {"packet_loss_rate": loss_rate}
        row.update(_ci_dict(run_qrl_acc,  "qrl_accuracy"))
        row.update(_ci_dict(run_ppo_acc,  "ppo_accuracy"))
        row.update(_ci_dict(run_qrl_safe, "qrl_local_safety"))
        row.update(_ci_dict(run_ppo_safe, "ppo_local_safety"))
        row.update(_ci_dict(run_qrl_glob, "qrl_global_efficiency"))
        row.update(_ci_dict(run_ppo_glob, "ppo_global_efficiency"))
        row["accuracy_gap_mean"] = round(
            row["qrl_accuracy_mean"] - row["ppo_accuracy_mean"], 4)
        row["safety_gap_mean"] = round(
            row["qrl_local_safety_mean"] - row["ppo_local_safety_mean"], 4)
        seq_loss_results.append(row)

    results["sequence_sensitivity"] = seq_loss_results

    if verbose:
        _print_summary(results)

    return results


def _print_summary(results: Dict):
    n_runs = results.get("metadata", {}).get("n_runs", "?")
    print("\n" + "="*70)
    print(f"EXPERIMENT RESULTS SUMMARY  (n_runs={n_runs}, 95% CI shown)")
    print("="*70)

    print("\n[EXP 1] Latency vs Decision Accuracy")
    print(f"{'Latency(ms)':<14} {'QRL Acc (95% CI)':<26} {'PPO Acc (95% CI)':<26} {'QRL Adv'}")
    for r in results["latency_sweep"]:
        adv = r["qrl_accuracy_mean"] - r["ppo_accuracy_mean"]
        qrl_ci = f"{r['qrl_accuracy_mean']:.4f} [{r['qrl_accuracy_ci95_lower']:.4f},{r['qrl_accuracy_ci95_upper']:.4f}]"
        ppo_ci = f"{r['ppo_accuracy_mean']:.4f} [{r['ppo_accuracy_ci95_lower']:.4f},{r['ppo_accuracy_ci95_upper']:.4f}]"
        print(f"{r['latency_ms']:<14} {qrl_ci:<26} {ppo_ci:<26} +{adv:.4f}")

    print("\n[EXP 2] Packet Loss vs Decision Accuracy")
    print(f"{'Loss Rate':<12} {'QRL Acc':<26} {'PPO Acc'}")
    for r in results["packet_loss_sweep"]:
        qrl_ci = f"{r['qrl_accuracy_mean']:.4f} [{r['qrl_accuracy_ci95_lower']:.4f},{r['qrl_accuracy_ci95_upper']:.4f}]"
        ppo_ci = f"{r['ppo_accuracy_mean']:.4f} [{r['ppo_accuracy_ci95_lower']:.4f},{r['ppo_accuracy_ci95_upper']:.4f}]"
        print(f"{r['packet_loss_rate']:<12.2f} {qrl_ci:<26} {ppo_ci}")

    print("\n[EXP 3] QKD Security Under MITM Attack")
    print(f"{'Attack Rate':<13} {'QKD Acc':<12} {'No-QKD Acc':<14} {'Tamper(NoQKD)'}")
    for r in results["security_experiment"]:
        print(f"{r['attack_rate']:<13.1f} {r['qkd_accuracy_mean']:.4f} [{r['qkd_accuracy_ci95_lower']:.4f},{r['qkd_accuracy_ci95_upper']:.4f}]   "
              f"{r['no_qkd_accuracy_mean']:.4f}         {r['no_qkd_tamper_rate']:.4f}")

    print("\n[EXP 4] Combined Stress Scenarios")
    print(f"{'Scenario':<16} {'QRL+QKD':<12} {'PPO':<12} {'QKD Gain'}")
    for r in results["combined_stress"]:
        print(f"{r['scenario']:<16} {r['qrl_with_qkd_accuracy_mean']:.4f} [{r['qrl_with_qkd_accuracy_ci95_lower']:.4f},{r['qrl_with_qkd_accuracy_ci95_upper']:.4f}]   "
              f"{r['ppo_accuracy_mean']:.4f}   +{r['qkd_security_gain_mean']:.4f}")

    print("\n[EXP 5] PPO Lambda Sweep vs QRL")
    print(f"{'λ':<8} {'Scenario':<12} {'PPO Acc':<12} {'QRL Acc':<12} {'QRL Adv':<10} {'PPO SafeEff Ratio'}")
    for r in results["ppo_lambda_sweep"]:
        print(f"{r['lambda_param']:<8} {r['scenario']:<12} "
              f"{r['ppo_accuracy_mean']:.4f}±{r['ppo_accuracy_std']:.4f}   "
              f"{r['qrl_accuracy_mean']:.4f}±{r['qrl_accuracy_std']:.4f}   "
              f"+{r['qrl_advantage_mean']:.4f}     "
              f"{r['ppo_safety_efficiency_ratio']:.4f}")

    if "sequence_sensitivity" in results:
        print("\n[EXP 6] SeQUeNCe Sensitivity — Packet Loss vs QRL/PPO Accuracy Gap")
        print(f"{'Loss':<8} {'QRL Acc':<28} {'PPO Acc':<28} {'Gap':<10} {'Safety Gap'}")
        for r in results["sequence_sensitivity"]:
            qrl_ci = f"{r['qrl_accuracy_mean']:.4f} [{r['qrl_accuracy_ci95_lower']:.4f},{r['qrl_accuracy_ci95_upper']:.4f}]"
            ppo_ci = f"{r['ppo_accuracy_mean']:.4f} [{r['ppo_accuracy_ci95_lower']:.4f},{r['ppo_accuracy_ci95_upper']:.4f}]"
            print(f"{r['packet_loss_rate']:<8.2f} {qrl_ci:<28} {ppo_ci:<28} "
                  f"+{r['accuracy_gap_mean']:.4f}    +{r['safety_gap_mean']:.4f}")


def save_results(results: Dict, path: str = "experiment_results.json"):
    """Save results to JSON with an auto-generated timestamped copy."""
    with open(path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nResults saved to {path}")

    # Also write a timestamped copy so runs are never overwritten
    ts = results.get("metadata", {}).get("timestamp", time.strftime("%Y%m%dT%H%M%S"))
    ts_safe = ts.replace(":", "").replace("-", "")
    ts_path = path.replace(".json", f"_{ts_safe}.json")
    with open(ts_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"Timestamped copy saved to {ts_path}")


if __name__ == "__main__":
    print("Cloud5 Digital Twin — SeQUeNCe + QKD Experiment Suite")
    print("FGCU | Quantum Communication-Aware Digital Twin\n")
    results = run_experiments(n_readings=200, n_runs=10, verbose=True)
    save_results(results, path="experiment_results_v2.json")
